import test from 'node:test';
import assert from 'node:assert/strict';
import {Script} from 'node:vm';
import {encounterSelection,encounterPool,encounterDraftRecord,randomEncounter,encounterPrompt,encounterScene,submitEncounter} from '../opening-encounter-model.js';
import {buildEncounterRegex,buildEncounterDocument} from '../opening-encounter.js';
const config={scope:'fixture',mapUrl:'https://example.org/map.webp',premise:'普通江湖相遇',places:[{id:'home',name:'小楼',description:'常住的小院',people:['a','b'],map:[40,40],scenes:['甲事件','乙事件','丙事件']},{id:'bridge',name:'桥头',description:'城外桥边',people:['b','c'],map:[60,60]}],people:[{id:'a',name:'甲',group:'住客',description:'爱喝茶。'},{id:'b',name:'乙',group:'街坊',description:'会做面。'},{id:'c',name:'丙',group:'行客',description:'远道来访。'}]};
const draft={place:'home',person:'a',scope:'nearby',note:'雨后'};
function fixture(){const chat=[{mes:'【江湖偶遇簿】'}],calls=[];let id='one',version='original';return {chat,calls,change:()=>{id='two';},edit:()=>{version='changed';},host:{busy:false,pending:'',identity:()=>id,user:()=> '玩家',messages:()=>chat,snapshot:()=>version,check:identity=>{if(identity!==id)throw Error('switched');},save:async()=>{calls.push('save');},generate:async prompt=>{calls.push('generate');assert.match(prompt,/开场地点/);return '生成的正文';},commit:async(text,selection)=>{calls.push('commit');chat[0]={mes:text,selection};}}};}
test('random keeps unrequested dimensions and does not repeat the same person',()=>{const a=randomEncounter(config,draft,'place',()=>0);assert.equal(a.place,'bridge');assert.equal(a.person,'a');const b=randomEncounter(config,draft,'person',()=>0);assert.equal(b.person,'b');assert.equal(b.place,'home');assert.equal(b.names,'');assert.deepEqual(encounterPool(config,draft).map(x=>x.id),['a','b']);});
test('custom multiple people and concrete event survive draft save and reach prompt',()=>{const a=encounterSelection(config,{...draft,names:'甲、丙',event:2,action:'observe',visited:true});const record=JSON.parse(JSON.stringify(encounterDraftRecord(config,a)));assert.equal(record.bookScope,'fixture');assert.deepEqual(encounterSelection(config,record),a);const prompt=encounterPrompt(config,a);assert.match(prompt,/主要出场人物：甲、丙/);assert.match(prompt,/丙事件/);assert.match(prompt,/先看看/);assert.doesNotMatch(prompt,/随机安排一件事/);assert.match(prompt,/不替玩家/);});
test('scene immediately describes arrival, people, event and selected action',()=>{const a=encounterScene(config,{...draft,action:'approach'});assert.match(a.text,/你来到小楼/);assert.match(a.text,/你看见了甲/);assert.match(a.text,/甲事件/);assert.match(a.text,/上前问问/);});
test('generate then commit opening without appending a user prompt message',async()=>{const f=fixture();await submitEncounter(config,draft,f.host);assert.deepEqual(f.calls,['save','generate','commit']);assert.equal(f.chat.length,1);assert.equal(f.chat[0].mes,'生成的正文');assert.equal(f.host.busy,false);});
test('double click cannot generate twice',async()=>{const f=fixture();let release;f.host.generate=()=>new Promise(r=>{release=r;});const first=submitEncounter(config,draft,f.host);await Promise.resolve();await assert.rejects(submitEncounter(config,draft,f.host),/请稍等/);release('正文');await first;assert.equal(f.calls.filter(x=>x==='commit').length,1);});
test('switching chats during generation never writes to another chat',async()=>{const f=fixture();f.host.generate=async()=>{f.change();return '保留正文';};await assert.rejects(submitEncounter(config,draft,f.host),/switched/);assert.equal(f.chat[0].mes,'【江湖偶遇簿】');assert.equal(f.host.pending,'保留正文');});
test('editing/swiping the greeting during generation prevents overwrite',async()=>{const f=fixture();f.host.generate=async()=>{f.edit();return '正文';};await assert.rejects(submitEncounter(config,draft,f.host),/已变化/);assert.ok(!f.calls.includes('commit'));});
test('a new message during generation prevents writing the opening',async()=>{const f=fixture();f.host.generate=async()=>{f.chat.push({mes:'新消息'});return '正文';};await assert.rejects(submitEncounter(config,draft,f.host),/已变化/);assert.ok(!f.calls.includes('commit'));});
test('failed/empty generation leaves original opening intact and allows retry',async()=>{for(const result of ['',null]){const f=fixture();f.host.generate=async()=>result;await assert.rejects(submitEncounter(config,draft,f.host),/没有收到/);assert.equal(f.host.busy,false);assert.equal(f.chat[0].mes,'【江湖偶遇簿】');f.host.generate=async()=> '重试正文';await submitEncounter(config,draft,f.host);assert.equal(f.chat[0].mes,'重试正文');}});
test('failed save never calls a model or changes the greeting',async()=>{const f=fixture();f.host.save=async()=>{throw Error('save failed');};await assert.rejects(submitEncounter(config,draft,f.host),/save failed/);assert.equal(f.calls.length,0);});
test('opening export renders external raster and contains executable escaped script',()=>{const hostile={...config,premise:'</script><img src=x onerror=alert(1)>'};const rule=buildEncounterRegex(hostile);assert.deepEqual(rule.placement,[2]);assert.equal(rule.markdownOnly,true);assert.match(rule.replaceString,/<img id="map-image" src="https:\/\/example.org\/map.webp"/);assert.doesNotMatch(rule.replaceString,/<svg|data:image|写入酒馆输入框|此地人物|全部人物/);for(const doc of [rule.replaceString,buildEncounterDocument(hostile,{preview:true})]){assert.match(doc,/<body>/);assert.match(doc,/<\/body>/);const scripts=[...doc.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,1);new Script(scripts[0][1]);}});
