(() => {
  'use strict';
  const editions=[
    {id:'bookshop',issue:'第 016 期 · 午后版',time:'初夏 / 16:20',location:'⌖ 街角书店',weather:'晴 · 微风',icon:'☀',portrait:0,name:'林见夏',headline:'靠窗的位置，今天依旧为你留着。',summary:'书店刚结束午后的整理。林见夏抱着笔记本，目光已经第三次落在门口。河边的花开了，她似乎有一个小小的邀请。',energy:'充沛',mood:'期待',relation:'熟悉的同行者',value:72,thoughtTitle:'“绕一点远路，也没关系。”',thought:'如果你也不着急的话，今天能不能一起沿着河边慢慢走？',outfit:'鼠尾草绿开衫、奶油色碎花裙，别着小叶子发夹。',action:'整理好笔记本，等待与你一起出门。',relationNote:'会记得你爱看的书，也会把窗边的座位空下来。',relationDetail:'她已经不再问你要不要坐下，而是自然地把另一杯茶推到你手边。熟悉感藏在这些很小的习惯里。',thoughtDetail:'她把邀请写在便签背面，又轻轻划掉了。比起直接说出口，她更希望你先发现今天适合散步。',plan:'沿河散步，买一束小雏菊。',tip:'河边风轻，适合把回家的路走慢一点。',items:[['📓','缎带手记','随身记录','封面系着绿缎带，最新一页夹着一片刚压平的叶子。','问问林见夏，手记里最近记下了什么。'],['🗝','铜色小钥匙','书店物件','书店后门的钥匙，钥匙圈上挂着褪色的猫咪吊饰。','向林见夏询问书店后院的故事。'],['🌼','雏菊书签','一份小礼物','一张手作书签，花瓣压得很平，背面留着一句没署名的祝福。','问林见夏，这张雏菊书签是不是为我准备的。']]},
    {id:'station',issue:'第 017 期 · 夜间版',time:'初夏 / 21:45',location:'⌖ 旧车站月台',weather:'夜 · 小雨',icon:'☂',portrait:50,name:'沈予舟',headline:'末班车还没来，有人替你留了一把伞。',summary:'月台广播刚刚响过。沈予舟把折好的地图收进口袋，向有灯光的长椅挪了一点，身旁放着一把还没撑开的伞。',energy:'略有倦意',mood:'平静',relation:'逐渐信赖',value:58,thoughtTitle:'“不赶路，也算一种旅行。”',thought:'如果雨一直下，就在这里多待一会儿。反正这次的终点还没有定。',outfit:'浅蓝衬衫、奶油色旅行外套，挎包上挂着指南针。',action:'确认列车时刻，把干燥的长椅位置留给你。',relationNote:'话不多，但在安排旅程时，已经会为你多考虑一步。',relationDetail:'地图上的路线被改过一次，新路线经过你昨天提起的海边。你没再提，他却记了下来。',thoughtDetail:'他其实已经查好了附近的小旅馆。只是想把今晚去哪里这件事交给你决定。',plan:'雨停后去海边，寻找仍亮着灯的小店。',tip:'月台边有积水，走近灯光下会更好辨路。',items:[['🗺','折角地图','行程线索','沿海的路线被铅笔描了两遍，一个小镇旁画着星号。','请沈予舟讲讲地图上标星的小镇。'],['☂','深色雨伞','随身用品','一把很大的伞，伞柄缠着防滑的细绳。','和沈予舟撑同一把伞，走到车站出口。'],['🎫','旧车票','旅途纪念','夹在钱包里的旧车票，日期已经模糊，终点是海边。','问沈予舟为什么一直留着这张旧车票。']]}
  ];
  const $=id=>document.getElementById(id);let current=0,opened=false,selectedAction='';const saved=new Set();
  try{const value=JSON.parse(localStorage.getItem('moment-gazette-bookmarks')||'[]');if(Array.isArray(value))value.filter(id=>editions.some(e=>e.id===id)).forEach(id=>saved.add(id));}catch{}
  function bookmarkView(){const active=saved.has(editions[current].id);$('bookmark').setAttribute('aria-pressed',active);$('bookmark').textContent=active?'★ 已收藏这一期':'☆ 收藏这一期';}
  function setOpen(value){opened=value;$('paper').classList.toggle('open',value);$('inside').inert=!value;['fold-button','cover-button'].forEach(id=>$(id).setAttribute('aria-expanded',value));$('fold-button').textContent=value?'折好收起 ↙':'摊开报纸 ↗';$('fold-hint').textContent=value?'点击头版，可以重新折好 ↑':'沿折线打开 · 还有 5 则近况 ↓';$('page-count').textContent=value?'01 — 04 / 04':'01 / 01';}
  function annotate(title,text,action){$('annotation-title').textContent=title;$('annotation-text').textContent=text;selectedAction=action;$('annotation').hidden=false;$('annotation').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}
  function addDraft(text){const field=$('draft');field.value=field.value.trimEnd()+(field.value.trim()?'\n':'')+text;field.dispatchEvent(new Event('input',{bubbles:true}));$('draft-status').textContent='已添入来信，可以继续修改。';field.focus();}
  function render(){const e=editions[current];for(const key of ['issue','time','location','weather','headline','summary','energy','mood','relation','thought','outfit','action','plan','tip'])$(key).textContent=e[key];$('caption').textContent=e.name+' / 本期人物';$('portrait').style.backgroundPosition=e.portrait+'% 50%';$('weather-icon').textContent=e.icon;$('thought-title').textContent=e.thoughtTitle;$('relation-number').textContent=e.value;$('relation-title').textContent=e.relation;$('relation-note').textContent=e.relationNote;$('annotation').hidden=true;selectedAction='';$('classifieds').replaceChildren();e.items.forEach(item=>{const b=document.createElement('button');b.className='classified';const icon=document.createElement('span');icon.textContent=item[0];const body=document.createElement('div');const title=document.createElement('b');title.textContent=item[1];const kind=document.createElement('small');kind.textContent=item[2]+' · 点开查看 ↗';body.append(title,kind);b.append(icon,body);b.onclick=()=>annotate(item[1],item[3],item[4]);$('classifieds').append(b);});document.querySelectorAll('[data-edition]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.edition)===current));bookmarkView();}
  $('fold-button').onclick=() =>setOpen(!opened);$('cover-button').onclick=()=>setOpen(!opened);
  document.querySelectorAll('[data-edition]').forEach(b=>b.onclick=()=>{current=Number(b.dataset.edition);render();});
  document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>{const e=editions[current];if(b.dataset.story==='thought')annotate(e.name+'的言外之意',e.thoughtDetail,'回应'+e.name+'刚才没有说出口的邀请。');else annotate('那些相处的小细节',e.relationDetail,'和'+e.name+'聊聊最近一起经历的小事。');});
  $('close-annotation').onclick=()=>{$('annotation').hidden=true;};$('annotation-action').onclick=()=>{if(selectedAction)addDraft(selectedAction);};$('plan-draft').onclick=()=>addDraft('和'+editions[current].name+'约好：'+editions[current].plan);
  $('copy').onclick=async()=>{if(!$('draft').value.trim()){$('draft-status').textContent='先写一点内容，再复制。';return;}try{await navigator.clipboard.writeText($('draft').value);$('draft-status').textContent='来信已复制。';}catch{$('draft').focus();$('draft').select();$('draft-status').textContent='已选中文字，请手动复制。';}};
  $('bookmark').onclick=()=>{const id=editions[current].id;if(saved.has(id))saved.delete(id);else saved.add(id);bookmarkView();try{localStorage.setItem('moment-gazette-bookmarks',JSON.stringify([...saved]));}catch{$('bookmark').textContent=saved.has(id)?'★ 仅本次收藏':'☆ 收藏这一期';}};
  render();setOpen(false);
})();
